# This CloudBuild will be triggered by push to the branch "develop"
#

steps:
  - name: node
    entrypoint: npm
    args: ['install']
    dir: $_FUNCTION_DIR
    id: INSTALL

  - name: node
    entrypoint: npm
    args: [ 'run', 'build' ]
    dir: $_FUNCTION_DIR
    id: BUILD

  - name: node
    entrypoint: npm
    args: [ 'test' ]
    dir: $_FUNCTION_DIR
    id: TEST

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    args:
      - gcloud
      - functions
      - deploy
      - $_FUNCTION_NAME
      - --region=$_FUNCTION_REGION
      - --trigger-http
      - --runtime=$_FUNCTION_RUNTIME
      - --project=$_FUNCTION_PROJECT
      - --entry-point=myFuncHandler
      - --allow-unauthenticated
    dir: $_FUNCTION_DIR
    id: DEPLOY

substitutions:
  _FUNCTION_PROJECT : test-func-336618 # This is project ID not a name!
  _FUNCTION_NAME    : function-1
  _FUNCTION_REGION  : europe-central2
  _FUNCTION_RUNTIME : nodejs16
  _FUNCTION_DIR : myFunc1
